name: docs
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - sphinx=3.5.4=pyhd3eb1b0_0
  - sphinx_rtd_theme=0.5.2=pyhd8ed1ab_1
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.4=pyhd3eb1b0_0
